[package]
name = "umili"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "Mutate and inspect Rust data structures"
repository = "https://github.com/shigma/umili"
documentation = "https://docs.rs/umili"

[features]
default = ["derive"]
derive = []

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
umili-derive = { version = "0.1.1", path = "../derive" }

